"""rename order column to order_index

Revision ID: 5ec557fcdd8f
Revises: 7b7848dc7e5b
Create Date: 2026-09-27 10:51:13.003917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec557fcdd8f'
down_revision: Union[str, Sequence[str], None] = '7b7848dc7e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('stopovers', sa.Column('order_index', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_stopovers_ride_city_order'), table_name='stopovers')
    op.create_index('ix_stopovers_ride_city_order', 'stopovers', ['ride_id', 'city_name', 'order_index'], unique=False)
    op.drop_column('stopovers', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stopovers', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('ix_stopovers_ride_city_order', table_name='stopovers')
    op.create_index(op.f('ix_stopovers_ride_city_order'), 'stopovers', ['ride_id', 'city_name', 'order'], unique=False)
    op.drop_column('stopovers', 'order_index')
    op.alter_column('rides', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
