"""add seats_remaining and updated_at columns

Revision ID: 79b4b6e7d16f
Revises: 1b2b950ee07c
Create Date: 2026-09-16 15:10:16.488122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79b4b6e7d16f'
down_revision: Union[str, Sequence[str], None] = '1b2b950ee07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_stopovers_id'), table_name='ride_stopovers')
    op.drop_index(op.f('ix_ride_stopovers_ride_id'), table_name='ride_stopovers')
    op.drop_table('ride_stopovers')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_admin_logs_id'), table_name='admin_logs')
    op.drop_table('admin_logs')
    op.add_column('bookings', sa.Column('car_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('travel_date', sa.Date(), nullable=False))
    op.drop_index(op.f('ix_bookings_passenger_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_ride_id'), table_name='bookings')
    op.create_foreign_key(None, 'bookings', 'cars', ['car_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bookings', 'ride_date')
    op.drop_column('bookings', 'fare')
    op.create_foreign_key(None, 'car_photos', 'cars', ['car_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ride_occurrences', 'seats_remaining',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_ride_occurrences_ride_id'), table_name='ride_occurrences')
    op.alter_column('rides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_rides_car_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_constraint(op.f('rides_return_ride_id_fkey'), 'rides', type_='foreignkey')
    op.create_foreign_key(None, 'rides', 'users', ['driver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rides', 'cars', ['car_id'], ['id'], ondelete='CASCADE')
    op.drop_column('rides', 'return_ride_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('return_ride_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.create_foreign_key(op.f('rides_return_ride_id_fkey'), 'rides', 'rides', ['return_ride_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_car_id'), 'rides', ['car_id'], unique=False)
    op.alter_column('rides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ride_occurrences_ride_id'), 'ride_occurrences', ['ride_id'], unique=False)
    op.alter_column('ride_occurrences', 'seats_remaining',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'car_photos', type_='foreignkey')
    op.add_column('bookings', sa.Column('fare', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('ride_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_index(op.f('ix_bookings_ride_id'), 'bookings', ['ride_id'], unique=False)
    op.create_index(op.f('ix_bookings_passenger_id'), 'bookings', ['passenger_id'], unique=False)
    op.drop_column('bookings', 'travel_date')
    op.drop_column('bookings', 'car_id')
    op.create_table('admin_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('admin_logs_admin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_logs_pkey'))
    )
    op.create_index(op.f('ix_admin_logs_id'), 'admin_logs', ['id'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_super_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey'))
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('ride_stopovers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ride_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('ride_stopovers_ride_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ride_stopovers_pkey'))
    )
    op.create_index(op.f('ix_ride_stopovers_ride_id'), 'ride_stopovers', ['ride_id'], unique=False)
    op.create_index(op.f('ix_ride_stopovers_id'), 'ride_stopovers', ['id'], unique=False)
    # ### end Alembic commands ###
