"""add max_back_seat_passengers and instant_booking to rides

Revision ID: 7b7848dc7e5b
Revises: 
Create Date: 2026-09-27 03:17:48.278712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7848dc7e5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('max_back_seat_passengers', sa.Integer(), nullable=True))
    op.add_column('rides', sa.Column('instant_booking', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'instant_booking')
    op.drop_column('rides', 'max_back_seat_passengers')
    # ### end Alembic commands ###
