"""check_schema_changes

Revision ID: cf8c2d35f640
Revises: 79b4b6e7d16f
Create Date: 2026-09-21 15:26:18.176451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8c2d35f640'
down_revision: Union[str, Sequence[str], None] = '79b4b6e7d16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_photos', 'is_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_photos', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
